# Run notifier from the latest docker image, tagging the user in the step summary
name: notify

on:
  workflow_dispatch:
  schedule:
    - cron: "15 23 * * 1-5" # 4:15pm MT on every day-of-week from Monday through Friday.

env:
  COMPANIES: >-
    airbnb
    airtable
    chanzuckerberginitiative
    discord
    netflix

jobs:
  notify:
    runs-on: ubuntu-22.04
    timeout-minutes: 15
    env:
      LOCAL_STORAGE_PATH: .storage
      ARTIFACT_NAME: cache
    steps:
      - name: Make Storage Directory
        run: mkdir -p ${{ env.LOCAL_STORAGE_PATH }}

      - uses: actions/checkout@v4

      - uses: ./.github/actions/download-artifact
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: ${{ env.ARTIFACT_NAME }}
          path: ${{ env.LOCAL_STORAGE_PATH }}

      - name: Run Notifier
        uses: docker://ghcr.io/bradgwest/job-notifier:latest
        with:
          args: >-
            --storage-backend LocalStorage
            --local-storage-path ${{ env.LOCAL_STORAGE_PATH }}
            --notifier-backend GithubStepSummaryNotifier
            --github-user ${{ github.event_name == 'workflow_dispatch' && github.actor || github.repository_owner }}
            --companies ${{ env.COMPANIES }}
        timeout-minutes: 10

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ${{ env.LOCAL_STORAGE_PATH }}
